### ISSUE TITLE
Change the way scriptlets are parametrized

### ISSUE THREAD

**Issue by nebkam** [nebkam/netsuite-restlet-php-sdk#22]
Currently, scripts are parametrized by their IDs in `config.json`
What we were afraid of, `deploy` URL param can (and does) differ in sandbox VS development
So, how do we handle this?
1. Parametrize the full URL? 
2. Parametrize the path?
3. Parametrize script ID and deploy ID as a touple?
4. Something else?

In any case, it will have to be a BC breaking change, since we're changing `int ` to `string` or `array` or something else..
Please comment your thoughts @silvesterk @Shinhan @Vodzo @tabonka

**Comment by silvesterk** [comment]
I am not sure if deployment is unique to the script id it is calling since the current development implementation has different deployment ids for different scripts? 

If that is a leftover of something that was being tested in the development and the deployment stays the same for all scripts I believe the solution would be to just create a deployment parameter (the sandbox example only uses deployment = 1)

Example:

{
  "account": "",
  "consumerKey": "",
  "consumerSecret": "",
  "accessTokenKey": "",
  "accessTokenSecret": "",
  "signatureMethod": "HMAC-SHA1",
  "deployment": 1,
  "restletMap": {
    "createDeleteContact": 0,
    "createDeleteCustomer": 0,
    "createDeleteSalesOrder": 0,
    "downloadPdf": 0,
    "getSalesOrder": 0,
    "savedSearchCustomers": 0,
    "savedSearchGeneric": 0,
    "savedSearchItems": 0,
    "suiteQL": 0
  }
}

If that is not the case and script id-s use different deployment ids I feel like parametrizing script id and deployment id in a object would be the cleanest solution.

Example:
{
  "account": "",
  "consumerKey": "",
  "consumerSecret": "",
  "accessTokenKey": "",
  "accessTokenSecret": "",
  "signatureMethod": "HMAC-SHA1",
  "restletMap": {
    "createDeleteContact": {
        "deployment": 1,
        "scriptId": 0
    }
  }
}

**Comment by nebkam** [comment]
AFAIK `deploy` param is scriptlet-dependent. This explains why only some scriptlets in the `dev` env have different `deploy` values.
The fact that all `sandbox` scriptlets have `deploy=1` is, in my opinion, just a coincidence, because RSM didn't make any updates to them (yet)

**Comment by Shinhan** [comment]
> in my opinion, just a coincidence

Can we discuss this during the regular friday meeting?

**Comment by Vodzo** [comment]
If `deploy` and `scriptId` are the only parameters that can differ between environments then it seems that suggestion #3 is the best fit for this use case.
I would argue for the syntax to be something like this
```
...
"restletMap": {
    ...
    "getSalesOrder": {
        deploy: 1,
        scriptId: 2
     },
    ...
}
```
It does seem redundant but it is more clear.

But I agree with @Shinhan, this should be discussed with RSM just to be sure how everything works.

**Comment by Shinhan** [comment]
Also, I just heard they changed signature method from sha1 to sha256 and only on sandbox! Does this need to be another parameter in the config? We'll see tomorrow.

**Comment by nebkam** [comment]
@Shinhan It's already added in v2 - [commit](https://github.com/nebkam/netsuite-restlet-php-sdk/commit/9041842cc870f0466183657e5c3de2c669372fd2) | [release](https://github.com/nebkam/netsuite-restlet-php-sdk/releases/tag/2.2.0)
It can be backported to v1 branch

**Comment by Shinhan** [comment]
OK, second problem was that account Id is somewhere _ and elsewhere - and it turns out json config needs it written as _ and not - like I first thought.

**Comment by Shinhan** [comment]
After this meeting it seems we need the deployId/scriptId tuples.

**Comment by nebkam** [comment]
@Shinhan Per Zoran's screenshot, `Account ID` is written as "555555_AB"
It's being normalized in the SDK to "555555-ab" when uset as Restlet URL fragment.
Just use `Account ID` from Netsuite interface and you're good to go

**Comment by nebkam** [comment]
@Shinhan For clarity, I'm OK with renaming the config option from `account` to `accountId`

**Comment by nebkam** [comment]
`v2` change released - https://github.com/nebkam/netsuite-restlet-php-sdk/releases/tag/2.3.0

**Comment by nebkam** [comment]
`v1` change released - https://github.com/nebkam/netsuite-restlet-php-sdk/releases/tag/1.3.0
