### ISSUE TITLE
how would I use this to post to a restlet that's deployed?

### ISSUE THREAD

**Issue by dmcmillin** [nebkam/netsuite-restlet-php-sdk#37]
I have an deployed restlet that accepts basic json as a post. Which example would work best for this? Thanks ahead of time!!!

**Comment by nebkam** [comment]
Have a look at any method in `ApiService` that sends a POST (for example [`createContact`](https://github.com/nebkam/netsuite-restlet-php-sdk/blob/main/src/ApiService.php#L86))
Make sure that your domain class matches the expected JSON structure (in our example [`ContactForm`](https://github.com/nebkam/netsuite-restlet-php-sdk/blob/main/src/Model/Contact/ContactForm.php))
so that it can be serialized adequately.

If you want to go deeper, have a look at [`ApiClient::post`](https://github.com/nebkam/netsuite-restlet-php-sdk/blob/main/src/ApiClient.php#L67) that uses [Guzzle](https://docs.guzzlephp.org/en/stable/) under the hood to send the JSON payload.

**Comment by nebkam** [comment]
@dmcmillin Do you have any more questions? :)
